# Generated by Django 2.2.3 on 2019-10-20 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0004_auto_20191017_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='lostinfo',
            name='image_path',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
