# Generated by Django 2.2.3 on 2019-10-23 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0005_lostinfo_image_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='lostinfo',
            name='image_obj',
            field=models.ImageField(default=1, upload_to='iamge_file'),
            preserve_default=False,
        ),
    ]
